#include "KeyProvider.hpp"

const sf::Keyboard::Key KeyProvider::intToKeys[128] = 
{
    Keyboard::Unknown, // 0
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::BackSpace,
    Keyboard::Tab,
    Keyboard::Unknown, // 10
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown, // 20
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Escape,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown, // 30
    Keyboard::Unknown,
    Keyboard::Space,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Quote,
    Keyboard::Unknown, // 40
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Add,
    Keyboard::Comma,
    Keyboard::Dash,
    Keyboard::Period,
    Keyboard::Slash,
    Keyboard::Num0,
    Keyboard::Num1,
    Keyboard::Num2,  // 50
    Keyboard::Num3,
    Keyboard::Num4,
    Keyboard::Num5,
    Keyboard::Num6,
    Keyboard::Num7,
    Keyboard::Num8,
    Keyboard::Num9,
    Keyboard::Unknown,
    Keyboard::SemiColon,
    Keyboard::Unknown, // 60
    Keyboard::Equal,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::A,
    Keyboard::B,
    Keyboard::C,
    Keyboard::D,
    Keyboard::E,
    Keyboard::F,        // 70
    Keyboard::G,
    Keyboard::H,
    Keyboard::I,
    Keyboard::J,
    Keyboard::K,
    Keyboard::L,
    Keyboard::M,
    Keyboard::N,
    Keyboard::O,
    Keyboard::P,        // 80
    Keyboard::Q,
    Keyboard::R,
    Keyboard::S,
    Keyboard::T,
    Keyboard::U,
    Keyboard::V,
    Keyboard::W,
    Keyboard::X,
    Keyboard::Y,
    Keyboard::Z,        // 90
    Keyboard::LBracket,
    Keyboard::BackSlash,
    Keyboard::RBracket,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::A,
    Keyboard::B,
    Keyboard::C,
    Keyboard::D,        // 100
    Keyboard::E,
    Keyboard::F,
    Keyboard::G,
    Keyboard::H,
    Keyboard::I,
    Keyboard::J,
    Keyboard::K,
    Keyboard::L,
    Keyboard::M,
    Keyboard::N,        // 110
    Keyboard::O,
    Keyboard::P,
    Keyboard::Q,
    Keyboard::R,
    Keyboard::S,
    Keyboard::T,
    Keyboard::U,
    Keyboard::V,
    Keyboard::W,
    Keyboard::X,        // 120
    Keyboard::Y,
    Keyboard::Z,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Unknown,
    Keyboard::Tilde,
    Keyboard::Unknown,  // 127
};