<sliderStyle name="default">
	<mouseRect left="8" top="-3" width="26" height="36" />
	<value min="0" max="100" width="83"/>
	<idle backroundtexture="GuiElements" backroundsrcx="742" backroundsrcy="96" 
		backroundwidth="118" backroundheight="22" 
		backroundoffsetx="8" backroundoffsety="8" 
		slidertexture="GuiElements" slidersrcx="860" slidersrcy="104" 
		sliderwidth="32" sliderheight="46" 
		slideroffsetx="0" slideroffsety="-1" />
	<active backroundtexture="GuiElements" backroundsrcx="742" backroundsrcy="66" 
		backroundwidth="124" backroundheight="30" 
		backroundoffsetx="0" backroundoffsety="0" 
		slidertexture="GuiElements" slidersrcx="984" slidersrcy="82" 
		sliderwidth="38" sliderheight="54" 
		slideroffsetx="-6" slideroffsety="-9" />
</sliderStyle>