#include "KeyProvider.hpp"

const sf::Keyboard::Key KeyProvider::intToKeys[128] = 
{
    sf::Keyboard::Unknown, // 0
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::BackSpace,
    sf::Keyboard::Tab,
    sf::Keyboard::Unknown, // 10
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown, // 20
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Escape,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown, // 30
    sf::Keyboard::Unknown,
    sf::Keyboard::Space,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Quote,
    sf::Keyboard::Unknown, // 40
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Add,
    sf::Keyboard::Comma,
    sf::Keyboard::Dash,
    sf::Keyboard::Period,
    sf::Keyboard::Slash,
    sf::Keyboard::Num0,
    sf::Keyboard::Num1,
    sf::Keyboard::Num2,  // 50
    sf::Keyboard::Num3,
    sf::Keyboard::Num4,
    sf::Keyboard::Num5,
    sf::Keyboard::Num6,
    sf::Keyboard::Num7,
    sf::Keyboard::Num8,
    sf::Keyboard::Num9,
    sf::Keyboard::Unknown,
    sf::Keyboard::SemiColon,
    sf::Keyboard::Unknown, // 60
    sf::Keyboard::Equal,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::A,
    sf::Keyboard::B,
    sf::Keyboard::C,
    sf::Keyboard::D,
    sf::Keyboard::E,
    sf::Keyboard::F,        // 70
    sf::Keyboard::G,
    sf::Keyboard::H,
    sf::Keyboard::I,
    sf::Keyboard::J,
    sf::Keyboard::K,
    sf::Keyboard::L,
    sf::Keyboard::M,
    sf::Keyboard::N,
    sf::Keyboard::O,
    sf::Keyboard::P,        // 80
    sf::Keyboard::Q,
    sf::Keyboard::R,
    sf::Keyboard::S,
    sf::Keyboard::T,
    sf::Keyboard::U,
    sf::Keyboard::V,
    sf::Keyboard::W,
    sf::Keyboard::X,
    sf::Keyboard::Y,
    sf::Keyboard::Z,        // 90
    sf::Keyboard::LBracket,
    sf::Keyboard::BackSlash,
    sf::Keyboard::RBracket,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::A,
    sf::Keyboard::B,
    sf::Keyboard::C,
    sf::Keyboard::D,        // 100
    sf::Keyboard::E,
    sf::Keyboard::F,
    sf::Keyboard::G,
    sf::Keyboard::H,
    sf::Keyboard::I,
    sf::Keyboard::J,
    sf::Keyboard::K,
    sf::Keyboard::L,
    sf::Keyboard::M,
    sf::Keyboard::N,        // 110
    sf::Keyboard::O,
    sf::Keyboard::P,
    sf::Keyboard::Q,
    sf::Keyboard::R,
    sf::Keyboard::S,
    sf::Keyboard::T,
    sf::Keyboard::U,
    sf::Keyboard::V,
    sf::Keyboard::W,
    sf::Keyboard::X,        // 120
    sf::Keyboard::Y,
    sf::Keyboard::Z,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Unknown,
    sf::Keyboard::Tilde,
    sf::Keyboard::Unknown,  // 127
};