<buttonStyle name="default">
	<mouseRect left="2" top="2" width="306" height="46" />
	<idle texture="GuiElements" srcx="0" srcy="0" width="317" height="58"
		offsetx="0" offsety="0"
		font="buttonIdleFont" fontoffsetx="0" fontoffsety="4" />
	<hover texture="GuiElements" srcx="317" srcy="0" width="317" height="58"
		offsetx="0" offsety="0"
		font="buttonHoverFont" fontoffsetx="0" fontoffsety="4" />
	<pressed texture="GuiElements" srcx="634" srcy="0" width="325" height="66"
		offsetx="-6" offsety="-6"
		font="buttonHoverFont" fontoffsetx="1" fontoffsety="5" />
</buttonStyle>