<include>
	<templates>
		<shapes>
			<shape name="spike_okpart" type="complex_polygon">
				<polygon>
					<vertex x="0" y="59" />
					<vertex x="8" y="32" />
					<vertex x="16" y="32" />
					<vertex x="23" y="59" />
				</polygon>
				<polygon>
					<vertex x="24" y="59" />
					<vertex x="32" y="32" />
					<vertex x="40" y="32" />
					<vertex x="47" y="59" />
				</polygon>
				<polygon>
					<vertex x="48" y="59" />
					<vertex x="56" y="32" />
					<vertex x="64" y="32" />
					<vertex x="71" y="59" />
				</polygon>
				<polygon>
					<vertex x="72" y="59" />
					<vertex x="80" y="32" />
					<vertex x="88" y="32" />
					<vertex x="95" y="59" />
				</polygon>
				<polygon>
					<vertex x="96" y="59" />
					<vertex x="104" y="32" />
					<vertex x="112" y="32" />
					<vertex x="119" y="59" />
				</polygon>
			</shape>
			<shape name="spike_killer" type="complex_polygon">
				<polygon>
					<vertex x="-52" y="32" />
					<vertex x="-48" y="19" />
					<vertex x="-47" y="19" />
					<vertex x="-44" y="32" />
				</polygon>
				<polygon>
					<vertex x="-28" y="32" />
					<vertex x="-24" y="19" />
					<vertex x="-23" y="19" />
					<vertex x="-20" y="32" />
				</polygon>
				<polygon>
					<vertex x="-4" y="32" />
					<vertex x="0" y="19" />
					<vertex x="1" y="19" />
					<vertex x="4" y="32" />
				</polygon>
				<polygon>
					<vertex x="20" y="32" />
					<vertex x="24" y="19" />
					<vertex x="25" y="19" />
					<vertex x="28" y="32" />
				</polygon>
				<polygon>
					<vertex x="44" y="32" />
					<vertex x="48" y="19" />
					<vertex x="49" y="19" />
					<vertex x="52" y="32" />
				</polygon>
			</shape>
			<shape name="spike_okpart2" type="complex_polygon">
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="8" y="27" />
					<vertex x="16" y="27" />
					<vertex x="23" y="0" />
				</polygon>
				<polygon>
					<vertex x="24" y="0" />
					<vertex x="32" y="27" />
					<vertex x="40" y="27" />
					<vertex x="47" y="0" />
				</polygon>
				<polygon>
					<vertex x="48" y="0" />
					<vertex x="56" y="27" />
					<vertex x="64" y="27" />
					<vertex x="71" y="0" />
				</polygon>
				<polygon>
					<vertex x="72" y="0" />
					<vertex x="80" y="27" />
					<vertex x="88" y="27" />
					<vertex x="95" y="0" />
				</polygon>
				<polygon>
					<vertex x="96" y="0" />
					<vertex x="104" y="27" />
					<vertex x="112" y="27" />
					<vertex x="119" y="0" />
				</polygon>
			</shape>
			<shape name="spike_killer2" type="complex_polygon">
				<polygon>
					<vertex x="-52" y="27" />
					<vertex x="-48" y="40" />
					<vertex x="-47" y="40" />
					<vertex x="-44" y="27" />
				</polygon>
				<polygon>
					<vertex x="-28" y="27" />
					<vertex x="-24" y="40" />
					<vertex x="-23" y="40" />
					<vertex x="-20" y="27" />
				</polygon>
				<polygon>
					<vertex x="-4" y="27" />
					<vertex x="0" y="40" />
					<vertex x="1" y="40" />
					<vertex x="4" y="27" />
				</polygon>
				<polygon>
					<vertex x="20" y="27" />
					<vertex x="24" y="40" />
					<vertex x="25" y="40" />
					<vertex x="28" y="27" />
				</polygon>
				<polygon>
					<vertex x="44" y="27" />
					<vertex x="48" y="40" />
					<vertex x="49" y="40" />
					<vertex x="52" y="27" />
				</polygon>
			</shape>
			<shape name="spike_okpart3" type="complex_polygon">
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="27" y="8" />
					<vertex x="27" y="16" />
					<vertex x="0" y="23" />
				</polygon>
				<polygon>
					<vertex x="0" y="24" />
					<vertex x="27" y="32" />
					<vertex x="27" y="40" />
					<vertex x="0" y="47" />
				</polygon>
				<polygon>
					<vertex x="0" y="48" />
					<vertex x="27" y="56" />
					<vertex x="27" y="64" />
					<vertex x="0" y="71" />
				</polygon>
				<polygon>
					<vertex x="0" y="72" />
					<vertex x="27" y="80" />
					<vertex x="27" y="88" />
					<vertex x="0" y="95" />
				</polygon>
				<polygon>
					<vertex x="0" y="96" />
					<vertex x="27" y="104" />
					<vertex x="27" y="112" />
					<vertex x="0" y="119" />
				</polygon>
			</shape>
			<shape name="spike_killer3" type="complex_polygon">
				<polygon>
					<vertex x="27" y="-52" />
					<vertex x="40" y="-48" />
					<vertex x="40" y="-47" />
					<vertex x="27" y="-44" />
				</polygon>
				<polygon>
					<vertex x="27" y="-28" />
					<vertex x="40" y="-24" />
					<vertex x="40" y="-23" />
					<vertex x="27" y="-20" />
				</polygon>
				<polygon>
					<vertex x="27" y="-4" />
					<vertex x="40" y="0" />
					<vertex x="40" y="1" />
					<vertex x="27" y="4" />
				</polygon>
				<polygon>
					<vertex x="27" y="20" />
					<vertex x="40" y="24" />
					<vertex x="40" y="25" />
					<vertex x="27" y="28" />
				</polygon>
				<polygon>
					<vertex x="27" y="44" />
					<vertex x="40" y="48" />
					<vertex x="40" y="49" />
					<vertex x="27" y="52" />
				</polygon>
			</shape>
			<shape name="spike_okpart4" type="complex_polygon">
				<polygon>
					<vertex x="60" y="0" />
					<vertex x="33" y="8" />
					<vertex x="33" y="16" />
					<vertex x="60" y="23" />
				</polygon>
				<polygon>
					<vertex x="60" y="24" />
					<vertex x="33" y="32" />
					<vertex x="33" y="40" />
					<vertex x="60" y="47" />
				</polygon>
				<polygon>
					<vertex x="60" y="48" />
					<vertex x="33" y="56" />
					<vertex x="33" y="64" />
					<vertex x="60" y="71" />
				</polygon>
				<polygon>
					<vertex x="60" y="72" />
					<vertex x="33" y="80" />
					<vertex x="33" y="88" />
					<vertex x="60" y="95" />
				</polygon>
				<polygon>
					<vertex x="60" y="96" />
					<vertex x="33" y="104" />
					<vertex x="33" y="112" />
					<vertex x="60" y="119" />
				</polygon>
			</shape>
			<shape name="spike_killer4" type="complex_polygon">
				<polygon>
					<vertex x="33" y="-52" />
					<vertex x="20" y="-48" />
					<vertex x="20" y="-47" />
					<vertex x="33" y="-44" />
				</polygon>
				<polygon>
					<vertex x="33" y="-28" />
					<vertex x="20" y="-24" />
					<vertex x="20" y="-23" />
					<vertex x="33" y="-20" />
				</polygon>
				<polygon>
					<vertex x="33" y="-4" />
					<vertex x="20" y="0" />
					<vertex x="20" y="1" />
					<vertex x="33" y="4" />
				</polygon>
				<polygon>
					<vertex x="33" y="20" />
					<vertex x="20" y="24" />
					<vertex x="20" y="25" />
					<vertex x="33" y="28" />
				</polygon>
				<polygon>
					<vertex x="33" y="44" />
					<vertex x="20" y="48" />
					<vertex x="20" y="49" />
					<vertex x="33" y="52" />
				</polygon>
			</shape>
		</shapes>

		<physics>
			<physic name="spike_okpart">
				<body type="static" angle="0" />
				<fixture density="0.5" friction="0.8" restitution="0.1" />
			</physic>
		</physics>

		<entities>
			<entity name="spike_okpart" rep="^O" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_okpart" />
				<animations>
					<animation texture="gravity_arrow" y="20" srcx="224" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="24" y="20" srcx="224" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="48" y="20" srcx="224" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="72" y="20" srcx="224" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="96" y="20" srcx="224" srcy="128" width="24" height="40" />
				</animations>
			</entity>
			<entity name="spike_okpart" rep="^X" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_killer" />
				<onCollision>
					<killBall />
				</onCollision>
			</entity>
			<entity name="spike_okpart2" rep="o^" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_okpart2" />
				<animations>
					<animation texture="gravity_arrow" y="0" srcx="248" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="24" y="0" srcx="248" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="48" y="0" srcx="248" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="72" y="0" srcx="248" srcy="128" width="24" height="40" />
					<animation texture="gravity_arrow" x="96" y="0" srcx="248" srcy="128" width="24" height="40" />
				</animations>
			</entity>
			<entity name="spike_okpart2" rep="x^" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_killer2" />
				<onCollision>
					<killBall />
				</onCollision>
			</entity>
			<entity name="spike_okpart3" rep="o>" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_okpart3" />
				<animations>
					<animation texture="gravity_arrow" x="0" y="0" srcx="183" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="0" y="24" srcx="183" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="0" y="48" srcx="183" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="0" y="72" srcx="183" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="0" y="96" srcx="183" srcy="128" width="40" height="24" />
				</animations>
			</entity>
			<entity name="spike_okpart3" rep="x>" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_killer3" />
				<onCollision>
					<killBall />
				</onCollision>
			</entity>
			<entity name="spike_okpart4" rep=">o" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_okpart4" />
				<animations>
					<animation texture="gravity_arrow" x="20" y="0" srcx="143" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="20" y="24" srcx="143" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="20" y="48" srcx="143" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="20" y="72" srcx="143" srcy="128" width="40" height="24" />
					<animation texture="gravity_arrow" x="20" y="96" srcx="143" srcy="128" width="40" height="24" />
				</animations>
			</entity>
			<entity name="spike_okpart4" rep=">x" type="entity" collideWithBall="true">
				<physics name="spike_okpart" shape="spike_killer4" />
				<onCollision>
					<killBall />
				</onCollision>
			</entity>
		</entities>
	</templates>
</include>