<include>
	<templates>
		<shapes>
			<shape name="wall_left" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="-20" />
				<vertex x="0" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_top" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="0" />
				<vertex x="-20" y="0" />
			</shape>
			<shape name="wall_right" type="polygon">
				<vertex x="0" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="20" />
				<vertex x="0" y="20" />
			</shape>
			<shape name="wall_bottom" type="polygon">
				<vertex x="-20" y="0" />
				<vertex x="20" y="0" />
				<vertex x="20" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			
			<shape name="wall_diagonal" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_diagonal1" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="20" />
			</shape>
			<shape name="wall_diagonal2" type="polygon">
				<vertex x="20" y="-20" />
				<vertex x="20" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_diagonal3" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			
			<shape name="wall_corner" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="0" />
			</shape>
			<shape name="wall_corner1" type="polygon">
				<vertex x="0" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="0" />
				<vertex x="0" y="0" />
			</shape>
			<shape name="wall_corner2" type="polygon">
				<vertex x="0" y="0" />
				<vertex x="20" y="0" />
				<vertex x="20" y="20" />
				<vertex x="0" y="20" />
			</shape>
			<shape name="wall_corner3" type="polygon">
				<vertex x="-20" y="0" />
				<vertex x="0" y="0" />
				<vertex x="0" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			
			<shape name="wall_vertex" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="0" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_vertex1" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="0" />
			</shape>
			<shape name="wall_vertex2" type="polygon">
				<vertex x="0" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="20" />
				<vertex x="0" y="0" />
			</shape>
			<shape name="wall_vertex3" type="polygon">
				<vertex x="-20" y="20" />
				<vertex x="0" y="0" />
				<vertex x="20" y="0" />
				<vertex x="20" y="20" />
			</shape>
			
			<shape name="wall_vertexi" type="polygon">
				<vertex x="0" y="20" />
				<vertex x="0" y="0" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="20" />
			</shape>
			<shape name="wall_vertexi1" type="polygon">
				<vertex x="-20" y="0" />
				<vertex x="0" y="0" />
				<vertex x="20" y="20" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_vertexi2" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_vertexi3" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="0" />
				<vertex x="0" y="0" />
			</shape>
			
			<shape name="wall_spike_left" type="polygon">
				<vertex x="-20" y="20" />
				<vertex x="0" y="0" />
				<vertex x="0" y="20" />
			</shape>
			<shape name="wall_spike_left1" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="0" />
			</shape>
			<shape name="wall_spike_left2" type="polygon">
				<vertex x="0" y="-20" />
				<vertex x="20" y="-20" />
				<vertex x="0" y="0" />
			</shape>
			<shape name="wall_spike_left3" type="polygon">
				<vertex x="0" y="0" />
				<vertex x="20" y="0" />
				<vertex x="20" y="20" />
			</shape>
			
			<shape name="wall_spike_right" type="polygon">
				<vertex x="0" y="0" />
				<vertex x="20" y="20" />
				<vertex x="0" y="20" />
			</shape>
			<shape name="wall_spike_right1" type="polygon">
				<vertex x="-20" y="0" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_spike_right2" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="-20" />
				<vertex x="0" y="0" />
			</shape>
			<shape name="wall_spike_right3" type="polygon">
				<vertex x="0" y="0" />
				<vertex x="20" y="-20" />
				<vertex x="20" y="0" />
			</shape>
			
			<shape name="wall_roof" type="polygon">
				<vertex x="-20" y="20" />
				<vertex x="0" y="0" />
				<vertex x="20" y="20" />
			</shape>
			<shape name="wall_roof1" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="-20" y="20" />
			</shape>
			<shape name="wall_roof2" type="polygon">
				<vertex x="-20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="20" y="-20" />
			</shape>
			<shape name="wall_roof3" type="polygon">
				<vertex x="20" y="-20" />
				<vertex x="0" y="0" />
				<vertex x="20" y="20" />
			</shape>
			
			<shape name="wall_inverse_roof" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_roof1" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_roof2" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_roof3" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
			</shape>
			
			<shape name="wall_inverse_corner_left" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="0" y="-20" />
					<vertex x="0" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="20" />
					<vertex x="0" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_left1" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="0" />
					<vertex x="-20" y="0" />
				</polygon>
				<polygon>
					<vertex x="-20" y="0" />
					<vertex x="0" y="0" />
					<vertex x="-20" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_left2" type="complex_polygon">
				<polygon>
					<vertex x="0" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="20" />
					<vertex x="0" y="20" />
				</polygon>
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="0" y="-20" />
					<vertex x="0" y="0" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_left3" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="0" />
					<vertex x="20" y="0" />
					<vertex x="20" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="0" />
				</polygon>
			</shape>
			
			<shape name="wall_inverse_corner_right" type="complex_polygon">
				<polygon>
					<vertex x="0" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="20" />
					<vertex x="0" y="20" />
				</polygon>
				<polygon>
					<vertex x="-20" y="20" />
					<vertex x="0" y="0" />
					<vertex x="0" y="20" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_right1" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="0" />
					<vertex x="20" y="0" />
					<vertex x="20" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="0" y="0" />
					<vertex x="-20" y="0" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_right2" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="0" y="-20" />
					<vertex x="0" y="20" />
					<vertex x="-20" y="20" />
				</polygon>
				<polygon>
					<vertex x="0" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="0" y="0" />
				</polygon>
			</shape>
			<shape name="wall_inverse_corner_right3" type="complex_polygon">
				<polygon>
					<vertex x="-20" y="-20" />
					<vertex x="20" y="-20" />
					<vertex x="20" y="0" />
					<vertex x="-20" y="0" />
				</polygon>
				<polygon>
					<vertex x="0" y="0" />
					<vertex x="20" y="0" />
					<vertex x="20" y="20" />
				</polygon>
			</shape>
		</shapes>

		<physics>
			<physic name="wall_norT">
				<body type="static" angle="0" />
				<fixture density="0.1" friction="0.8" restitution="0.5" />
			</physic>
		</physics>

		<entities>
			<entity name="nort_wall_left" rep="na">
				<physics name="wall_norT" shape="wall_left" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_edge" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_top" rep="nw">
				<physics name="wall_norT" shape="wall_top" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_edge" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_right" rep="nd">
				<physics name="wall_norT" shape="wall_right" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_edge" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_bottom" rep="nx">
				<physics name="wall_norT" shape="wall_bottom" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_edge" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_right_lower" rep="nc">
				<physics name="wall_norT" shape="wall_corner2" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_vertex" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_left_lower" rep="ny">
				<physics name="wall_norT" shape="wall_corner3" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_vertex" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_top_left" rep="nq">
				<physics name="wall_norT" shape="wall_corner" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_vertex" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_top_right" rep="ne">
				<physics name="wall_norT" shape="wall_corner1" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_vertex" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall" rep="nr">
				<physics name="wall_norT" shape="wall_vertex" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_left" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nt">
				<physics name="wall_norT" shape="wall_vertex1" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_left" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="ng">
				<physics name="wall_norT" shape="wall_vertex2" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_left" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nf">
				<physics name="wall_norT" shape="wall_vertex3" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_left" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall" rep="nz">
				<physics name="wall_norT" shape="wall_vertexi" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_right" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nu">
				<physics name="wall_norT" shape="wall_vertexi1" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_right" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nj">
				<physics name="wall_norT" shape="wall_vertexi2" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_right" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nh">
				<physics name="wall_norT" shape="wall_vertexi3" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_corner_right" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall" rep="n7">
				<physics name="wall_norT" shape="wall_diagonal" />
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall" rep="n9">
				<physics name="wall_norT" shape="wall_diagonal1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal" rotate="true">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="n3">
				<physics name="wall_norT" shape="wall_diagonal2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="n1">
				<physics name="wall_norT" shape="wall_diagonal3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall" rep="ni">
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal_corner" rotate="false" x="-40" y="-40"/>
					<animation spritesheet="walls_nort" sprite="norT_diagonal_glow" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="no">
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal_corner" rotate="false" x="40" y="-40">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
					<animation spritesheet="walls_nort" sprite="norT_diagonal_glow" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nl">
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal_corner" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
					<animation spritesheet="walls_nort" sprite="norT_diagonal_glow" rotate="false" x="-40" y="-40"/>
				</animations>
			</entity>
			<entity name="nort_wall" rep="nk">
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_diagonal_corner" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
					<animation spritesheet="walls_nort" sprite="norT_diagonal_glow" rotate="false" x="40" y="-40">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="n8">
				<physics name="wall_norT" shape="wall_spike_left"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_left" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="n6">
				<physics name="wall_norT" shape="wall_spike_left1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_left" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="n2">
				<physics name="wall_norT" shape="wall_spike_left2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_left" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="n4">
				<physics name="wall_norT" shape="wall_spike_left3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_left" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="nv">
				<physics name="wall_norT" shape="wall_spike_right"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_right" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nb">
				<physics name="wall_norT" shape="wall_spike_right1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_right" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nn">
				<physics name="wall_norT" shape="wall_spike_right2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_right" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nm">
				<physics name="wall_norT" shape="wall_spike_right3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_spike_right" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="nQ">
				<physics name="wall_norT" shape="wall_roof"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_roof" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nW">
				<physics name="wall_norT" shape="wall_roof1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_roof" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nS">
				<physics name="wall_norT" shape="wall_roof2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_roof" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nA">
				<physics name="wall_norT" shape="wall_roof3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_roof" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="nE">
				<physics name="wall_norT" shape="wall_inverse_roof"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_roof" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nR">
				<physics name="wall_norT" shape="wall_inverse_roof1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_roof" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nF">
				<physics name="wall_norT" shape="wall_inverse_roof2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_roof" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nD">
				<physics name="wall_norT" shape="wall_inverse_roof3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_roof" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="nT">
				<physics name="wall_norT" shape="wall_inverse_corner_left"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_left" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nZ">
				<physics name="wall_norT" shape="wall_inverse_corner_left1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_left" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nH">
				<physics name="wall_norT" shape="wall_inverse_corner_left2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_left" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nG">
				<physics name="wall_norT" shape="wall_inverse_corner_left3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_left" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
			
			
			<entity name="nort_wall_spike" rep="nU">
				<physics name="wall_norT" shape="wall_inverse_corner_right"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_right" rotate="false"/>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nI">
				<physics name="wall_norT" shape="wall_inverse_corner_right1"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_right" rotate="false">
						<rotation>
							<static value="90" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nK">
				<physics name="wall_norT" shape="wall_inverse_corner_right2"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_right" rotate="false">
						<rotation>
							<static value="180" />
						</rotation>
					</animation>
				</animations>
			</entity>
			<entity name="nort_wall_spike" rep="nJ">
				<physics name="wall_norT" shape="wall_inverse_corner_right3"/>
				<animations>
					<animation spritesheet="walls_nort" sprite="nort_inverse_corner_right" rotate="false">
						<rotation>
							<static value="270" />
						</rotation>
					</animation>
				</animations>
			</entity>
		</entities>
	</templates>
</include>